# Generated by Django 4.2 on 2026-02-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ডাক্তারের পূর্ণ নাম', max_length=200, verbose_name='নাম')),
                ('qualification', models.TextField(help_text='শিক্ষাগত যোগ্যতা (HTML tags allowed)', verbose_name='যোগ্যতা')),
                ('specialty', models.CharField(help_text='বিশেষজ্ঞতার ক্ষেত্র', max_length=200, verbose_name='বিশেষত্ব')),
                ('schedule', models.TextField(help_text='চেম্বার সময়সূচী (HTML tags allowed)', verbose_name='সময়সূচী')),
                ('hospital', models.CharField(help_text='হাসপাতাল/ক্লিনিকের নাম', max_length=200, verbose_name='হাসপাতাল')),
                ('contact', models.CharField(help_text='ফোন নম্বর', max_length=200, verbose_name='যোগাযোগ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='সর্বশেষ আপডেট')),
                ('is_active', models.BooleanField(default=True, help_text='ডাক্তার তালিকায় দেখানো হবে কিনা', verbose_name='সক্রিয়')),
            ],
            options={
                'verbose_name': 'ডাক্তার',
                'verbose_name_plural': 'ডাক্তারগণ',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['name'], name='doctors_doc_name_17579e_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty'], name='doctors_doc_special_4b2702_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['hospital'], name='doctors_doc_hospita_30a1d3_idx'),
        ),
    ]
