# Generated by Django 4.2 on 2026-02-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, help_text='ডাক্তারের ছবি (না দিলে ডিফল্ট ছবি দেখাবে)', null=True, upload_to='doctor_images/', verbose_name='প্রোফাইল ছবি'),
        ),
    ]
