# Generated by Django 4.2 on 2026-02-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_address',
            field=models.TextField(blank=True, help_text='হাসপাতাল/ক্লিনিকের ঠিকানা (Optional)', null=True, verbose_name='হাসপাতাল ঠিকানা'),
        ),
    ]
