# Generated by Django 4.2 on 2026-02-01 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0003_doctor_hospital_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '১'), (2, '২'), (3, '৩'), (4, '৪'), (5, '৫')], verbose_name='রেটিং')),
                ('comment', models.TextField(help_text='আপনার অভিজ্ঞতা লিখুন', verbose_name='মন্তব্য')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='রিভিউ করার সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেট করার সময়')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors.doctor', verbose_name='ডাক্তার')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ইউজার')),
            ],
            options={
                'verbose_name': 'রিভিউ',
                'verbose_name_plural': 'রিভিউসমূহ',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='যোগ করার সময়')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='ডাক্তার')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ইউজার')),
            ],
            options={
                'verbose_name': 'পছন্দের ডাক্তার',
                'verbose_name_plural': 'পছন্দের ডাক্তারগণ',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'doctor')},
            },
        ),
    ]
