# Generated by Django 4.2 on 2026-02-02 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0004_review_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('saturday', 'শনিবার'), ('sunday', 'রবিবার'), ('monday', 'সোমবার'), ('tuesday', 'মঙ্গলবার'), ('wednesday', 'বুধবার'), ('thursday', 'বৃহস্পতিবার'), ('friday', 'শুক্রবার')], max_length=20, verbose_name='সপ্তাহের দিন')),
                ('start_time', models.TimeField(verbose_name='শুরুর সময়')),
                ('end_time', models.TimeField(verbose_name='শেষ সময়')),
                ('is_available', models.BooleanField(default=True, verbose_name='উপলব্ধ')),
                ('max_appointments', models.IntegerField(default=5, verbose_name='সর্বোচ্চ এপয়েন্টমেন্ট')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'সময়সূচী',
                'verbose_name_plural': 'সময়সূচীসমূহ',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='এপয়েন্টমেন্টের তারিখ')),
                ('patient_name', models.CharField(max_length=200, verbose_name='রোগীর নাম')),
                ('patient_age', models.IntegerField(verbose_name='রোগীর বয়স')),
                ('patient_phone', models.CharField(max_length=20, verbose_name='ফোন নম্বর')),
                ('problem_description', models.TextField(verbose_name='সমস্যার বিবরণ')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমাণ'), ('confirmed', 'নিশ্চিত'), ('cancelled', 'বাতিল'), ('completed', 'সম্পন্ন')], default='pending', max_length=20, verbose_name='স্ট্যাটাস')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেট হয়েছে')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='অ্যাডমিন নোট')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='doctors.timeslot')),
            ],
            options={
                'verbose_name': 'এপয়েন্টমেন্ট',
                'verbose_name_plural': 'এপয়েন্টমেন্টসমূহ',
                'ordering': ['-appointment_date', '-created_at'],
                'unique_together': {('doctor', 'appointment_date', 'time_slot')},
            },
        ),
    ]
