# Generated by Django 4.2 on 2026-02-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_timeslot_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='নাম')),
                ('name_english', models.CharField(blank=True, max_length=100, verbose_name='English Name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='স্লাগ')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('icon', models.CharField(default='fa-stethoscope', help_text='Font Awesome class (e.g., fa-heart)', max_length=50, verbose_name='আইকন')),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class', max_length=20, verbose_name='রং')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower number = higher priority)', verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেট হয়েছে')),
            ],
            options={
                'verbose_name': 'ক্যাটেগরি',
                'verbose_name_plural': 'ক্যাটেগরিসমূহ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='এই ডাক্তার যে সব ক্যাটেগরিতে আছেন', related_name='doctors', to='doctors.category', verbose_name='ক্যাটেগরিসমূহ'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='primary_category',
            field=models.ForeignKey(blank=True, help_text='মূল বিশেষত্ব ক্যাটেগরি', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctors', to='doctors.category', verbose_name='প্রধান ক্যাটেগরি'),
        ),
        migrations.CreateModel(
            name='CategoryKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='কীওয়ার্ড')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='doctors.category', verbose_name='ক্যাটেগরি')),
            ],
            options={
                'verbose_name': 'ক্যাটেগরি কীওয়ার্ড',
                'verbose_name_plural': 'ক্যাটেগরি কীওয়ার্ডসমূহ',
                'ordering': ['category', 'keyword'],
                'unique_together': {('category', 'keyword')},
            },
        ),
    ]
