# Generated by Django 4.2 on 2026-02-02 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_category_doctor_categories_doctor_primary_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='view_count',
            field=models.IntegerField(default=0, help_text='মোট কতবার ডাক্তার প্রোফাইল দেখা হয়েছে', verbose_name='ভিউ সংখ্যা'),
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='সার্চ টার্ম')),
                ('result_count', models.IntegerField(default=0, verbose_name='ফলাফল সংখ্যা')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='সার্চের সময়')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='আইপি ঠিকানা')),
                ('category_filter', models.CharField(blank=True, max_length=100, verbose_name='ক্যাটেগরি ফিল্টার')),
                ('clicked_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to='doctors.doctor', verbose_name='ক্লিক করা ডাক্তার')),
            ],
            options={
                'verbose_name': 'সার্চ কোয়েরি',
                'verbose_name_plural': 'সার্চ কোয়েরিসমূহ',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='দেখার সময়')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='আইপি ঠিকানা')),
                ('user_agent', models.TextField(blank=True, verbose_name='ব্রাউজার তথ্য')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='রেফারার')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='সেশন কী')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='doctors.doctor', verbose_name='ডাক্তার')),
            ],
            options={
                'verbose_name': 'ডাক্তার ভিউ',
                'verbose_name_plural': 'ডাক্তার ভিউসমূহ',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='তারিখ')),
                ('total_views', models.IntegerField(default=0, verbose_name='মোট ভিউ')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='ইউনিক ভিজিটর')),
                ('total_searches', models.IntegerField(default=0, verbose_name='মোট সার্চ')),
                ('unique_searches', models.IntegerField(default=0, verbose_name='ইউনিক সার্চ')),
                ('most_searched_term', models.CharField(blank=True, max_length=255, verbose_name='সর্বাধিক সার্চ টার্ম')),
                ('most_viewed_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_stats_as_top', to='doctors.doctor', verbose_name='সর্বাধিক দেখা ডাক্তার')),
            ],
            options={
                'verbose_name': 'দৈনিক পরিসংখ্যান',
                'verbose_name_plural': 'দৈনিক পরিসংখ্যানসমূহ',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['-searched_at'], name='doctors_sea_searche_34b5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['query'], name='doctors_sea_query_85de46_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorview',
            index=models.Index(fields=['doctor', '-viewed_at'], name='doctors_doc_doctor__590207_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorview',
            index=models.Index(fields=['ip_address', 'viewed_at'], name='doctors_doc_ip_addr_b514ab_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorview',
            index=models.Index(fields=['-viewed_at'], name='doctors_doc_viewed__29c4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['-date'], name='doctors_dai_date_ba60c5_idx'),
        ),
    ]
