# Generated by Django 4.2 on 2026-02-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctor_view_count_searchquery_doctorview_dailystats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-is_emergency_available', '-is_24_7_available', 'name'], 'verbose_name': 'ডাক্তার', 'verbose_name_plural': 'ডাক্তারগণ'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='emergency_note',
            field=models.TextField(blank=True, help_text='জরুরি সেবা সম্পর্কিত বিশেষ তথ্য (ঐচ্ছিক)', verbose_name='জরুরি নোট'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='জরুরি যোগাযোগের ফোন নম্বর (ঐচ্ছিক)', max_length=20, verbose_name='জরুরি ফোন নম্বর'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_24_7_available',
            field=models.BooleanField(default=False, help_text='২৪ ঘণ্টা সেবা দেন কিনা', verbose_name='২৪/৭ উপলব্ধ'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_emergency_available',
            field=models.BooleanField(default=False, help_text='জরুরি প্রয়োজনে এই ডাক্তার পাওয়া যাবে কিনা', verbose_name='জরুরি সেবা উপলব্ধ'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_emergency_update',
            field=models.DateTimeField(blank=True, help_text='জরুরি তথ্য শেষ আপডেট হওয়ার সময়', null=True, verbose_name='শেষ আপডেট'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_emergency_available'], name='doctors_doc_is_emer_901d81_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_24_7_available'], name='doctors_doc_is_24_7_1bdbaa_idx'),
        ),
    ]
