# Generated by Django 4.2 on 2026-02-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_alter_doctor_options_doctor_emergency_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'সোমবার'), (1, 'মঙ্গলবার'), (2, 'বুধবার'), (3, 'বৃহস্পতিবার'), (4, 'শুক্রবার'), (5, 'শনিবার'), (6, 'রবিবার')], help_text='0=সোমবার, 6=রবিবার', verbose_name='সপ্তাহের দিন')),
                ('start_time', models.TimeField(help_text='জরুরি সেবা শুরুর সময় (24-hour format)', verbose_name='শুরুর সময়')),
                ('end_time', models.TimeField(help_text='জরুরি সেবা শেষ সময় (24-hour format)', verbose_name='শেষ সময়')),
                ('is_emergency', models.BooleanField(default=True, help_text='এই সময়ে জরুরি সেবা দেন কিনা', verbose_name='জরুরি সেবা')),
                ('is_active', models.BooleanField(default=True, help_text='এই সময়সূচী বর্তমানে চালু আছে কিনা', verbose_name='সক্রিয়')),
                ('notes', models.CharField(blank=True, help_text='অতিরিক্ত তথ্য (ঐচ্ছিক)', max_length=200, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেট হয়েছে')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_schedules', to='doctors.doctor', verbose_name='ডাক্তার')),
            ],
            options={
                'verbose_name': 'জরুরি সময়সূচী',
                'verbose_name_plural': 'জরুরি সময়সূচীসমূহ',
                'ordering': ['doctor', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='ছুটি শুরুর তারিখ', verbose_name='শুরুর তারিখ')),
                ('end_date', models.DateField(help_text='ছুটি শেষ তারিখ', verbose_name='শেষ তারিখ')),
                ('reason', models.CharField(blank=True, help_text='ছুটির কারণ (ঐচ্ছিক)', max_length=200, verbose_name='কারণ')),
                ('is_emergency_available', models.BooleanField(default=False, help_text='ছুটিতেও জরুরি সেবা দেবেন কিনা', verbose_name='জরুরি সেবা উপলব্ধ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctors.doctor', verbose_name='ডাক্তার')),
            ],
            options={
                'verbose_name': 'ডাক্তার ছুটি',
                'verbose_name_plural': 'ডাক্তার ছুটিসমূহ',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='emergencyschedule',
            index=models.Index(fields=['doctor', 'day_of_week', 'is_active'], name='doctors_eme_doctor__5a182e_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyschedule',
            index=models.Index(fields=['is_active', 'is_emergency'], name='doctors_eme_is_acti_e90a03_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorleave',
            index=models.Index(fields=['doctor', 'start_date', 'end_date'], name='doctors_doc_doctor__15dbad_idx'),
        ),
    ]
