# Generated by Django 4.2.7 on 2026-02-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_emergencyschedule_doctorleave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emergency_note_en',
            field=models.TextField(blank=True, help_text='Special information about emergency services in English (Optional)', verbose_name='Emergency Note (English)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_address_en',
            field=models.TextField(blank=True, help_text='Hospital/Clinic address in English', verbose_name='Hospital Address (English)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_en',
            field=models.CharField(blank=True, help_text='Hospital/Clinic name in English', max_length=200, verbose_name='Hospital (English)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_en',
            field=models.CharField(blank=True, help_text="Doctor's full name in English", max_length=200, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification_en',
            field=models.TextField(blank=True, help_text='Educational qualifications in English', verbose_name='Qualification (English)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='schedule_en',
            field=models.TextField(blank=True, help_text='Chamber schedule in English', verbose_name='Schedule (English)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_en',
            field=models.CharField(blank=True, help_text='Area of specialization in English', max_length=200, verbose_name='Specialty (English)'),
        ),
    ]
